[versions]
# libraries
junitBom = "5.11.3"
hamcrest = "3.0"
kotlinTest = "2.0.21"
mockk = "1.13.13"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.10.5"
kotlin = "2.3.0"
kover = "0.9.1"
qodana = "2024.1.9"

[libraries]
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine"}
junitJupiterParams = { group = "org.junit.jupiter", name = "junit-jupiter-params"}
junitJupiterSuite = { group = "org.junit.platform", name = "junit-platform-suite"}
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
