[versions]
# libraries
junitBom = "5.11.3"
hamcrest = "3.0"
kotlinTest = "2.0.21"
mockk = "1.13.13"
remoteRobot = "0.11.23"
loggingInterceptor = "4.12.0"
videoRecorderJunit5 = "2.0"

# plugins
changelog = "2.2.1"
intelliJPlatform = "2.5.0"
kotlin = "2.2.10"
kover = "0.8.3"
qodana = "2024.1.9"

[libraries]
junitBom = { group = "org.junit", name = "junit-bom", version.ref = "junitBom" }
junitJupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine"}
junitJupiterSuite = { group = "org.junit.platform", name = "junit-platform-suite"}
hamcrest = { group = "org.hamcrest", name = "hamcrest", version.ref = "hamcrest" }
kotlinTest = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }
remoteRobot = { group = "com.intellij.remoterobot", name = "remote-robot", version.ref = "remoteRobot" }
remoteFixtures = { group = "com.intellij.remoterobot", name = "remote-fixtures", version.ref = "remoteRobot" }
loggingInterceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "loggingInterceptor" }
videoRecorderJunit5 = { group = "com.automation-remarks", name = "video-recorder-junit5", version.ref = "videoRecorderJunit5" }

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
